import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Chat Interface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-background text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />

          <div className="flex pt-12">
            {/* Sidebar Navbar for Desktop */}
            <div className="hidden md:block w-64 border-r">
              <Navbar />
            </div>

            {/* Main Content */}
            <main className="flex-1 p-4 md:p-6">{children}</main>
          </div>

          {/* Bottom Navbar for Mobile */}
          <div className="md:hidden fixed bottom-0 left-0 w-full border-t bg-background z-50">
            <Navbar />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
